# network
arch: resnet18
net: attnseg
# train setting
optimizer: sgd
lr_base: 0.01
lr_decay: 0.9
momentum: 0.9
epoch: 40
step_per_epoch: -1 # -1 means walk through all data
validation_step: 10
batch_size: 4
evaluate_batch_size: 1
weight_decay: 0.0001

# dataset setting
im_size: 1024
crop_size: 520
grey_ratio: 0.1
query_label_names: 
  - hair
  - face 
  - lb
  - rb
  - le
  - re 
  - nose
  - ulip
  - imouth
  - llip
# aug_setting_name: aug_512_0.6_multi_person
# aug_ids: [0 , 1 , 2 , 3 , 4]
training_dataset:
  - HELEN_naive_merge_post
  - HELEN_merge
test_dataset:
  - HELEN_naive_merge_post
  - HELEN_merge