# network
arch: resnet101

# train setting
optimizer: sgd
lr_base: 0.01
lr_decay: 0.9
momentum: 0.9
epoch: 1
step_per_epoch: 1000 # -1 means walk through all data
validation_step: 50
batch_size: 24
weight_decay: 0.0001

# dataset setting
im_size: 512
crop_size: 520
grey_ratio: 0.1
query_label_names: [hair]
aug_setting_name: aug_512_0.6_multi_person