# network
arch: resnet101
multi_scale_loss: true
add_fc: False
self_attention: True
group_norm: True

# train setting
optimizer: sgd
lr_base: 0.01
lr_decay: 0.9
momentum: 0.9
epoch: 20
step_per_epoch: -1 # -1 means walk through all data
validation_step: 10
batch_size: 28
weight_decay: 0.0001

# dataset setting
im_size: 512
crop_size: 666
random_scale: 400
grey_ratio: 0.1
query_label_names: [hair]
aug_setting_name: aug_1.0_original
position_map: True
dataset_names:
  - HELENRelabeled